# Generated by Django 5.1.4 on 2024-12-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegge', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
