# Generated by Django 5.1.4 on 2024-12-19 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegge', '0009_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 12, 19, 20, 32, 58, 613606, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
