# Generated by Django 5.1.4 on 2024-12-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
